# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Yuxuan Zhu"
title_separator          : "-"
name                     : &name "Yuxuan Zhu"
description              : &description "Researcher at Shopee working on recommender systems and causality-inspired machine learning."
url                      : https://EthanChu7.github.io
baseurl                  : "/yuxuan.zhu.github.io"
repository               : "EthanChu7/yuxuan.zhu.github.io"
